### ISSUE TITLE
Use id in apis

### ISSUE THREAD

**Issue by itsmanojb** [Clean-Coder-AI/python-generator#13]
For the following APIs, change the `_name` fields to `_id` in payload and query params:

- GET /snippets
- GET /templates
- POST /snippet
- POST /template

E.g.
company_name, project_name... should be replaced with company_id, project_id and so on.
Reason: names are not unique, also the names are not available in the api-data-flow.

Query: why `company_name` is used instead of `org_name` in snippets/templates ?

**Comment by surajadh** [comment]
Now we have /snippet and /projectsnippet, /prompt and /projectprompt to create two different types of code snippets or prompts
